# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ARUui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ARUui(object):
    def setupUi(self, ARUui):
        ARUui.setObjectName("ARUui")
        ARUui.resize(1063, 607)
        self.centralwidget = QtWidgets.QWidget(ARUui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1061, 591))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.ARUui = QtWidgets.QPushButton(self.centralwidget)
        self.ARUui.setGeometry(QtCore.QRect(810, 550, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ARUui.setFont(font)
        self.ARUui.setStyleSheet("background-color: rgb(0, 86, 0);c")
        self.ARUui.setObjectName("ARUui")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 550, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 361, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:/e683f29e5eb2d87da457379948533a08.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 280, 301, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:/images.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 190, 241, 171))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:/image_processing20191029-12300-1uapa6r.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(440, 30, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(680, 30, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(800, 180, 201, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:/face-id-glitch.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        ARUui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ARUui)
        self.statusbar.setObjectName("statusbar")
        ARUui.setStatusBar(self.statusbar)

        self.retranslateUi(ARUui)
        QtCore.QMetaObject.connectSlotsByName(ARUui)

    def retranslateUi(self, ARUui):
        _translate = QtCore.QCoreApplication.translate
        ARUui.setWindowTitle(_translate("ARUui", "ARU"))
        self.ARUui.setText(_translate("ARUui", "Start"))
        self.pushButton_2.setText(_translate("ARUui", "Exit"))
        self.textBrowser.setHtml(_translate("ARUui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sitka Small\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sitka Small\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ARUui = QtWidgets.QMainWindow()
    ui = Ui_ARUui()
    ui.setupUi(ARUui)
    ARUui.show()
    sys.exit(app.exec_())
